### ISSUE TITLE
the java command requires a mounted proc fs (/proc).

### ISSUE THREAD

**Issue by pablosproject** [guysoft/CustomPiOS#124]
Hi, I tried installing open-jdk in my install `start_chroot_script` using `apt-get install -y default-jdk`, and I am getting the following error:

```
the java command requires a mounted proc fs (/proc).
dpkg: error processing package openjdk-11-jre-headless:armhf (--configure):
 installed openjdk-11-jre-headless:armhf package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of openjdk-11-jre:armhf:
 openjdk-11-jre:armhf depends on openjdk-11-jre-headless (= 11.0.9.1+1-1~deb10u2); however:
  Package openjdk-11-jre-headless:armhf is not configured yet.
```

Any idea where I should start looking to solve the issue?

**Comment by guysoft** [comment]
Hey,
Looks like this might require adding code to mount ``/proc``.

There is a solution suggested here:
https://stackoverflow.com/a/44572431/311268

The lines in CustomPiOS needed to change should go here:
https://github.com/guysoft/CustomPiOS/blob/devel/src/common.sh#L191

And something might need to go here:
https://github.com/guysoft/CustomPiOS/blob/devel/src/common.sh#L196

Do you think you can manage testing this?

**Comment by pablosproject** [comment]
I'll try get a minimal error out and try reproducing it, and then work on the solution, seems straightforward. Will work on this as soon that I have some spare time.

**Comment by guysoft** [comment]
Pushed a fix, please ping me if that solves it

**Comment by pablosproject** [comment]
Solved, working correctly. Thanks.
