### ISSUE TITLE
Force unmount mount points

### ISSUE THREAD

**Issue by pablosproject** [guysoft/CustomPiOS#131]
During the build process, it happened that the resources to unmount at this line were currently busy. https://github.com/guysoft/CustomPiOS/blob/c61b80e5dc27cf98daab55abfc6a77ac30d381da/src/common.sh#L229 

In my builds I solved with the following snippet, killing the process using the busy resource:
```
if [ "$RUN_IN_DOCKER" == "yes" ]; then
    # Release docker retained /dev
    fuser -cuk /dev
fi
```

Would it be harmful to force detach the mount point using `sudo unmount -lf $m`? Or at least catch it and show who is using the mount point in case of failing mount.

**Comment by guysoft** [comment]
That would be
```bash
if  [ -f /.dockerenv ]; then
    # Release docker retained /dev
    fuser -cuk /dev
fi
```

**Comment by pablosproject** [comment]
Does this apply to /proc also?

**Comment by guysoft** [comment]
@pablosproject I don't know, I don't think so, proc i think is not a normal OS, i think in a way its always busy.

**Comment by pablosproject** [comment]
In the related issue the problem was with `/proc` mount being busy. More in general, do you think we can overcome all issues by simply forcing unmount all mounted points?

**Comment by guysoft** [comment]
Unmounts fail for a reason.
"Errors should never pass silently.
Unless explicitly silenced."

**Comment by pablosproject** [comment]
Makes lot of sense
