### ISSUE TITLE
Question: is it possible to pull a docker image from a local docker registry during start_chroot_script

### ISSUE THREAD

**Issue by jsimonrichard** [guysoft/CustomPiOS#134]
Would it be possible to pull a custom docker image from a docker registry on my own computer during the `start_chroot_script` (or through some other method)? I would like that image to be accessible after the custom distro is installed even if there is no access to my docker registry at that time.

A couple of issues come to mind, but I'm not sure how to solve them.
* What is my host machine's IP address relative to the chroot environment (is it just `localhost`?)
* Would docker be accessible during `start_chroot_script`?
* Can the docker daemon be started in the chroot environment?

Thanks, in advance, for your help.

**Comment by guysoft** [comment]
Why would you want to do that?

**Comment by jsimonrichard** [comment]
The product I'm developing will be installed on the lower levels of factory networks. I can't guarantee these devices will have access to the internet when they're installed.

**Comment by guysoft** [comment]
You could try use something like this to ship the image as a tar. Then load it on boot:
https://stackoverflow.com/a/23938978/311268

**Comment by jsimonrichard** [comment]
Yeah, that's probably the way to go.

Thanks for the help.
