### ISSUE TITLE
Where does the image get created?

### ISSUE THREAD

**Issue by vivekanand1101** [guysoft/CustomPiOS#14]
When we finally use: ```<distro folder>/src/build_dist``` where does it create the image file? As far as i can see, there are no errors right now but, after the final line of output i am not able to see the image file 😕

**Comment by vivekanand1101** [comment]
ping?

**Comment by guysoft** [comment]
Sorry didnt see
in ``/src/workspace/imagename.img``. If using vagrant method or running ``./release`` a zip file would also be created.

Should really add this to the [FAQ in the wiki](https://github.com/guysoft/CustomPiOS/wiki/FAQ).

**Comment by guysoft** [comment]
[Added to FAQ](https://github.com/guysoft/CustomPiOS/wiki/FAQ)
