### ISSUE TITLE
raspian or raspios or debian?

### ISSUE THREAD

**Issue by steviehs** [guysoft/CustomPiOS#141]
http://downloads.raspberrypi.org/raspbian_lite/images/ - this is the place, where CustomPiOS downloads the latest image - hasn't received new images since Feb. 2020. Does anybody know why? 
What about https://raspi.debian.net/? Wouldn't this be the future way to go?

**Comment by cp2004** [comment]
Raspbian was renamed to Raspberry Pi OS, if you look through https://downloads.raspberrypi.org/ you will find `raspios_*` for the various different types of images

**Comment by guysoft** [comment]
What @cp2004 said, he equivalent to the url you posted is now:
https://downloads.raspberrypi.org/raspios_lite_armhf/images/

**Comment by steviehs** [comment]
Maybe it would be worth to change the URL to the raspios_lite images in make_custom_pi_os?
I think I will try soonish to switch our project to the debian images (though they are also not "official"), as this makes sense only on RPi4... let you know the results

**Comment by guysoft** [comment]
Thanks for pointing out!
Fixed

**Comment by steviehs** [comment]
nope, you should at least have tested it once :-)

**Comment by steviehs** [comment]
I have added a pull request, this was an easy one.

**Comment by guysoft** [comment]
Excellent, i missed the grep bit.
Merged reference #142

**Comment by steviehs** [comment]
Thanks for merging fast, so my build process will work again :-)

**Comment by guysoft** [comment]
BTW you might want to look in to the ubuntu 64-bit image if you are doing RaspberryPi 4-only stuff. 
might squeeze a little more performance out of it.

The make os script doesn't support it. But I maintain ubuntu to work for the OctoPi 64bit builds.
