### ISSUE TITLE
Remove flavor config system

### ISSUE THREAD

**Issue by guysoft** [guysoft/CustomPiOS#154]
Hey all,
To my knowloadge there is no one using the flavor build system, since you can just use the variant system.

Due to flag changes because of #151 I am alerting that I am planing to drop support for it.

If anyone has objections, is using it or has any other reason please object/support here.

**Comment by guysoft** [comment]
@mrbeam I can see this in your repos, are you still using it?

**Comment by guysoft** [comment]
Related https://github.com/mrbeam/BeamOS/issues/90

**Comment by guysoft** [comment]
Got an answer from MR bean that they are using legacy CustomPiOS and don't mind. Also it seems like no one else is using it. Dropping support.

**Comment by kraeml** [comment]
May you have to remove the paragraph in the wiki.

https://github.com/guysoft/CustomPiOS/wiki/Building#variant-flavors

**Comment by guysoft** [comment]
Thanks, done
