### ISSUE TITLE
Bullseye wifi doest connect

### ISSUE THREAD

**Issue by rodrigo2019** [guysoft/CustomPiOS#165]
Hello, I'm using [fluiddpi image](https://github.com/fluidd-core/FluiddPI) that is based on your image. I have two PI's, the first one uses the Buster version and it works fine. My problem is with the Bullseye version, it list all available wifi but doesn't connect.
My image didn't came with the iptables lib, I installed by myself but didn't solved.

Could you give me some tips?

Thanks you

**Comment by guysoft** [comment]
Can you provide a build.log output?

Thanks,

**Comment by rodrigo2019** [comment]
where is the path for the file?

**Comment by guysoft** [comment]
So please use the issue tracker of FluiddPi that maintain that image, this issue tracker is for building CustomPiOS images, not flashing and using them:
https://github.com/fluidd-core/FluiddPI/issues
