### ISSUE TITLE
Missing space in test for kernel type

### ISSUE THREAD

**Issue by robiwano** [guysoft/CustomPiOS#17]
In CustomPiOS/src/modules/kernel/end_chroot_script, the lines 53 and 59 have badly formatted second test, instead of:
`if [ "$KERNEL_TYPE" == "both" ] || ["$KERNEL_TYPE"  == "v6" ]; then`
it should read:
`if [ "$KERNEL_TYPE" == "both" ] || [ "$KERNEL_TYPE"  == "v6" ]; then`
Note the space between the second [ and ".

**Comment by guysoft** [comment]
I can fix it, but FYI pull requests are welcome.
