### ISSUE TITLE
When a module fails to build, CustomPiOS keeps building the other modules

### ISSUE THREAD

**Issue by guysoft** [guysoft/CustomPiOS#18]
A failure should halt the build, the problem happens because there is no testing in ``/distro/src/workspace/chroot_script`` that is generated by [execution_order.py](https://github.com/guysoft/CustomPiOS/blob/CustomPiOS/src/execution_order.py).

The code there should be improved.

**Comment by foosel** [comment]
Just ran into this as well. Was confused why my image wasn't working, then noticed that the OctoPi build had run into a network error half way through but no error was generated :/

**Comment by guysoft** [comment]
Yes, also @toddejohnson ran in to it. I was going to do this, even added [echo_red](https://github.com/guysoft/CustomPiOS/blob/CustomPiOS/src/common.sh#L24) and [echo_green](https://github.com/guysoft/CustomPiOS/blob/CustomPiOS/src/common.sh#L28) so we could actually print this in color, but never managed to capture the failures. If anyone has time to do this then awesome, if not I will get to it eventually.
