### ISSUE TITLE
Skip "user rename" on first boot and $BASE_USER

### ISSUE THREAD

**Issue by henrikbjorn** [guysoft/CustomPiOS#217]
Hey

Thanks for your work on this. I am new to the custom Raspberry PI Image world and I might be missing something :)

I have gotten the building process to work, and can create a image that can be written to an SD Card an booted up. Even build it via GitHub Actions with Docker.

However I am stuck with the "Please enter a new username:" dialog on first boot, which I would like to skip, since i have scripts in `/home/pi` (which seems to be the place to put them).

Also I noticed that `$BASE_USER` is not used in all modules (eg. base and gui, for auto login etc).

Would you accept a PR that uses `$BASE_USER` through out the modules?

**Comment by guysoft** [comment]
Indeed its a bug. if you have a particular module that is causing issues you are welcome to share it and I can take a look at fixing it.

**Comment by guysoft** [comment]
@henrikbjorn It works for you now?
