### ISSUE TITLE
Make release run on dist_build on default distro

### ISSUE THREAD

**Issue by guysoft** [guysoft/CustomPiOS#32]
Because people want their image to have the right name

**Comment by guysoft** [comment]
Less relevant now with the docker build method. Rather people just use that.

**Comment by s00500** [comment]
Hey @guysoft,

First of all AWESOME PROJECT, really like the structure, reminds me of buildroot, but with starting from a base image

I have run into the problem you have added as an issue yourself and wanted to ask why you never considered adding a release flag to the build_custom_os script ? adding a simple flag there would be a simple fix to the problem I believe... I can also submit a PR if you want, what do you think ?

Greetings,
Lukas
