### ISSUE TITLE
Doesn't seem to work with Stretch

### ISSUE THREAD

**Issue by tenten8401** [guysoft/CustomPiOS#4]
Fired this up in a clean install of Ubuntu 16.04 with a Raspbian Stretch image: https://www.raspberrypi.org/downloads/raspbian/, specifically the Raspbian Stretch With Desktop.

When building the .img file, it seems to just hang at a blinking cursor when booting on a pi.
All default setups.

**Comment by guysoft** [comment]
What distro are you building? The default example?

**Comment by tenten8401** [comment]
@guysoft I'm building the default example, no gui module.

**Comment by guysoft** [comment]
Works for me, can't reproduce.

Can you provide the build output?
Also attaching the scripts used to build so you can compare, includes the build.log.
[ExampleOS.tar.gz](https://github.com/guysoft/CustomPiOS/files/1309052/ExampleOS.tar.gz):

Proof of it running here
![20170917_145758](https://user-images.githubusercontent.com/325670/30520574-0a0a62dc-9bb9-11e7-9da0-79fddb987d1e.jpg)

**Comment by tenten8401** [comment]
Well that's baffling. Probably something I did on my end then.
Either way, I think I've got another solution in place for building images.

**Comment by guysoft** [comment]
What are you using,  if I may ask?

**Comment by tenten8401** [comment]
Just cloned the repo, ran through this: https://github.com/guysoft/CustomPiOS#build-a-distro-from-within-raspbian--debian--ubuntu--custompios-distros, dropped the image in there and built it. Used a Ubuntu 16.04 VirtualBox VM.

**Comment by guysoft** [comment]
Did you run ``make_custom_pi_os``?
I think you missed that step and built the template.

Also I was asking what were you using as an alternative?

**Comment by tenten8401** [comment]
I ran make_custom_pi_os and everything in that section I linked you, putting the stretch desktop image in before finnaly building the final image.

As for the alternative, I'm using https://github.com/RPi-Distro/pi-gen, which takes about 45 minutes to build on my system with apt caching.
