### ISSUE TITLE
Realpath does not exist in Debian 10

### ISSUE THREAD

**Issue by WheresWaldo** [guysoft/CustomPiOS#56]
There is no Buster version of realpath, https://packages.debian.org/search?keywords=realpath. It is also no longer included in coreutils.

In many instances you can use `readlink -f`
Can CustomPiOS be modified to use readlink instead of relying on realpath?

**Comment by guysoft** [comment]
This is already solved on the dev branch. commit: https://github.com/guysoft/CustomPiOS/commit/a2bff88148c548ed7876d3dc48448fcf48ad5e45
Make sure you are using the latest docker image.

Why is moving to ``readlink -f`` if realpath is already included?

**Comment by WheresWaldo** [comment]
I will close this
