### ISSUE TITLE
README instructions say "qemu-arm-static" when it should be "qemu-user-static"

### ISSUE THREAD

**Issue by cyrusadkisson** [guysoft/CustomPiOS#58]
Sent me on a wild goose chase for 30 minutes (partially bc I'm a noob, but still). The link itself links to qemu-user-static.

**Comment by guysoft** [comment]
Qenu-user-static is the software package. qemu-arm-static is the specific
binary.

>
1. This is listed in the docs here:
https://github.com/guysoft/CustomPiOS/wiki/Building#build-a-distro-from-within-raspbian--debian--ubuntu--custompios-distros

2. If you are compiling qemu then you need to know which target to compile

**Comment by guysoft** [comment]
Closing, issue is documented and no reply from OP
