### ISSUE TITLE
Keep the apt archive cache?

### ISSUE THREAD

**Issue by EternityForest** [guysoft/CustomPiOS#64]
I notice that there is a bind mount used to store the apt archive cache, but it also appears to be deleted with apt-get clean in several places.

Package caching is pretty useful and would speed builds a lot, is there a chance of using apt autoclean instead? The bindfs already prevents taking up space in the image itself, so it seems worth it.

Thanks again for the great product!

**Comment by guysoft** [comment]
Sure, any change you can provide a log so I can see which ``apt-get clean`` you are talking about?
Also its a time to note that pull requests are also welcome!

**Comment by guysoft** [comment]
Fixed with #65
