### ISSUE TITLE
pi 4 boot config.txt

### ISSUE THREAD

**Issue by asdf1nit** [guysoft/CustomPiOS#73]
With the update to the pi 4 board there is now another board revision.
https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

This commit https://github.com/guysoft/CustomPiOS/pull/53/commits fixed it for the previous revisions but it's now not applying the correct boot options correctly as the new boards are 03112(just got a couple new ones).
I'm currently building with all of that logic removed to see if it's still necessary in either pi 3/4. If it is still necessary I'll add to it to fix the current issue.

I'll submit a new pull with this fix if needed. I've got a couple pr's just about ready anyway.

**Comment by guysoft** [comment]
Thanks,  keep me posted!  I have no hardware to test that!

**Comment by asdf1nit** [comment]
Ok just got finished testing. Boot will boot with out any modification to the config.txt so the following block can be removed.
```
    check="$(sudo cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}' | sed -e 's/[a-c]//')"
    if [ "${check}" != "03111" ]; then
        sudo sed -i /boot/config.txt -e "s/^\#dtoverlay=vc4-kms-v3d/dtoverlay=vc4-kms-v3d/"
        printf "dtoverlay=vc4-kms-v3d\n" | sudo tee -a /boot/config.txt
    fi
```
The build was with gpu acceleration enabled. I can rebuild without gpu and test it later this week if you want to hold off but I'm not sure it's going to matter. Looks like the fksm driver is the preferred choice now and included in the default debian lite image on all variants of the pi based on the research I did to see if there was any newer preferred drivers.

**Comment by guysoft** [comment]
That code takes in to account older pis too. Might e better to add > than . Assuming all newer pis wont need it.
