### ISSUE TITLE
Enable copy instead of decompress of the image

### ISSUE THREAD

**Issue by s00500** [guysoft/CustomPiOS#84]
Hi,
The decompression of the zip file takes a rather long time in the build process... so my idea is to enable copy instead of decompress

I could supply a quick PR if you want to :-)

Greetings,
Lukas

**Comment by guysoft** [comment]
If you want to add something that is optional then sure. I am not sure what the implications if its default.  Might break build systems

**Comment by s00500** [comment]
See #85

**Comment by guysoft** [comment]
Merged
