### ISSUE TITLE
Admin Toolkit seems broken because of duplicate fi statement

### ISSUE THREAD

**Issue by s00500** [guysoft/CustomPiOS#87]
https://github.com/guysoft/CustomPiOS/blob/b1f9c18cbdb5eda0019814591495e9ad62a6e964/src/modules/admin-toolkit/start_chroot_script#L153

Does not look intended and breaks my build when using admin-toolkit, shall it be removed ?

**Comment by guysoft** [comment]
Its from a commit @asdf1nit did about a year ago:
https://github.com/guysoft/CustomPiOS/commit/124509df44310002668cb0a87f74c8aca9261d07#diff-4c1588d6ea919feb40b3cfea910aff18142aa2b9c204c0ad5a8ff962aa8a0149R152

I guess its his call, but it looks like a blunt syntax error. Would you like to PR for it or should I just remove it?

**Comment by s00500** [comment]
PR is ready :-)

**Comment by s00500** [comment]
Awesome =D
