### ISSUE TITLE
Admintoolkit uses fixed config

### ISSUE THREAD

**Issue by s00500** [guysoft/CustomPiOS#90]
I have one more issue with admin-toolkit: it seems to use a fixed config that can not be overrided

Is that the case or did I miss something ?

Other modules add their own config values as defaults that would not be used if set before, where as admin toolkit does set fixed values...

eg docker: 

```
[ -n "$DOCKER_COMPOSE" ] || DOCKER_COMPOSE=yes
```

**Comment by guysoft** [comment]
Ok, you are welcome to aDd functionality. PRs are welcome.
